spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true